targets:
  App:
    sources:
      - "OBAWidget.intentdefinition"    # includes intent in main app, necessary for displaying widget options on Springboard.
  OBAWidget:
    type: app-extension
    platform: iOS
    sources: ["."]
    dependencies:
      - target: OBAKitCore
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
    entitlements:
      path: OBAWidget.entitlements
    info:
      path: Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
